version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
    time: "17:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: NEST
    versions:
    - ">= 7.a, < 8"
